version: "3"
services:
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./deploy/caddy/Caddyfile:/etc/Caddyfile
      - ./static:/opt/backend/static
      - ../data/media:/opt/backend/media
    restart: always
    networks:
      - wallpapers
    depends_on:
      - backend
    ports:
      - "9999:80"
      - "9998:443"
      - "80:2015"
      - "443:2015"


  backend:
    build:
      context: ./
      dockerfile: deploy/Dockerfile
    restart: always
    command: >
      bash -c "
        python3 manage.py migrate &&
        python3 manage.py collectstatic --no-input &&
        gunicorn --reload -b 0.0.0.0:8000 wallpapers.wsgi --workers 4 --timeout 300 --log-level DEBUG
      "
    ports:
      - "8000:8050"
    volumes:
      - .:/code
      - ../data/media:/media
    networks:
      - wallpapers
    depends_on:
      - redis

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: always
    networks:
      - wallpapers
    volumes:
      - ../data/redis:/data

networks:
  wallpapers: