# Generated by Django 2.1.4 on 2018-12-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pictures.Tag'),
        ),
    ]
