# Generated by Django 2.1.4 on 2018-12-06 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20181206_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата загрузки'),
            preserve_default=False,
        ),
    ]
